// flow-typed signature: 51842916ecc7caf903a6725685120a29
// flow-typed version: <<STUB>>/coffee-reactify_v^4.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffee-reactify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffee-reactify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coffee-reactify/example/bar' {
  declare module.exports: any;
}

declare module 'coffee-reactify/example/bat' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coffee-reactify/example/bar.js' {
  declare module.exports: $Exports<'coffee-reactify/example/bar'>;
}
declare module 'coffee-reactify/example/bat.js' {
  declare module.exports: $Exports<'coffee-reactify/example/bat'>;
}
declare module 'coffee-reactify/index' {
  declare module.exports: $Exports<'coffee-reactify'>;
}
declare module 'coffee-reactify/index.js' {
  declare module.exports: $Exports<'coffee-reactify'>;
}
