// flow-typed signature: 29be7bc61f20c09d62ed5dec9a0e0d08
// flow-typed version: <<STUB>>/coffee-react-transform_v^4.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'coffee-react-transform'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'coffee-react-transform' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'coffee-react-transform/lib/entitydecode' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/helpers' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/htmlelements' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/parser' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/serialiser' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/stringescape' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/symbols' {
  declare module.exports: any;
}

declare module 'coffee-react-transform/lib/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'coffee-react-transform/index' {
  declare module.exports: $Exports<'coffee-react-transform'>;
}
declare module 'coffee-react-transform/index.js' {
  declare module.exports: $Exports<'coffee-react-transform'>;
}
declare module 'coffee-react-transform/lib/entitydecode.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/entitydecode'>;
}
declare module 'coffee-react-transform/lib/helpers.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/helpers'>;
}
declare module 'coffee-react-transform/lib/htmlelements.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/htmlelements'>;
}
declare module 'coffee-react-transform/lib/parser.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/parser'>;
}
declare module 'coffee-react-transform/lib/serialiser.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/serialiser'>;
}
declare module 'coffee-react-transform/lib/stringescape.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/stringescape'>;
}
declare module 'coffee-react-transform/lib/symbols.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/symbols'>;
}
declare module 'coffee-react-transform/lib/transformer.js' {
  declare module.exports: $Exports<'coffee-react-transform/lib/transformer'>;
}
