// flow-typed signature: 81aab929fa85ae6e7b2affd04ceb55e9
// flow-typed version: <<STUB>>/fs-extra_v^0.12.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-extra'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-extra' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-extra/lib/copy' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/create' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/ensure' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/index' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/json' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/mkdir' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/move' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/output' {
  declare module.exports: any;
}

declare module 'fs-extra/lib/remove' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-extra/lib/copy.js' {
  declare module.exports: $Exports<'fs-extra/lib/copy'>;
}
declare module 'fs-extra/lib/create.js' {
  declare module.exports: $Exports<'fs-extra/lib/create'>;
}
declare module 'fs-extra/lib/ensure.js' {
  declare module.exports: $Exports<'fs-extra/lib/ensure'>;
}
declare module 'fs-extra/lib/index.js' {
  declare module.exports: $Exports<'fs-extra/lib/index'>;
}
declare module 'fs-extra/lib/json.js' {
  declare module.exports: $Exports<'fs-extra/lib/json'>;
}
declare module 'fs-extra/lib/mkdir.js' {
  declare module.exports: $Exports<'fs-extra/lib/mkdir'>;
}
declare module 'fs-extra/lib/move.js' {
  declare module.exports: $Exports<'fs-extra/lib/move'>;
}
declare module 'fs-extra/lib/output.js' {
  declare module.exports: $Exports<'fs-extra/lib/output'>;
}
declare module 'fs-extra/lib/remove.js' {
  declare module.exports: $Exports<'fs-extra/lib/remove'>;
}
