// flow-typed signature: bd94ad3e3a61f5c2d35a32b6876d4cb7
// flow-typed version: <<STUB>>/html_v0.0.7/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'html'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'html' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'html/bin/html' {
  declare module.exports: any;
}

declare module 'html/lib/html' {
  declare module.exports: any;
}

declare module 'html/src/html' {
  declare module.exports: any;
}

// Filename aliases
declare module 'html/bin/html.js' {
  declare module.exports: $Exports<'html/bin/html'>;
}
declare module 'html/lib/html.js' {
  declare module.exports: $Exports<'html/lib/html'>;
}
declare module 'html/src/html.js' {
  declare module.exports: $Exports<'html/src/html'>;
}
