// flow-typed signature: c2932778da03bbbc2ffcef70af84ca24
// flow-typed version: <<STUB>>/node-watch_v^0.3.4/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-watch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-watch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-watch/lib/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-watch/index' {
  declare module.exports: $Exports<'node-watch'>;
}
declare module 'node-watch/index.js' {
  declare module.exports: $Exports<'node-watch'>;
}
declare module 'node-watch/lib/watch.js' {
  declare module.exports: $Exports<'node-watch/lib/watch'>;
}
