// flow-typed signature: 4cb45c245804eef59889600f29cd2104
// flow-typed version: <<STUB>>/parse-link-header_v^0.2.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'parse-link-header'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'parse-link-header' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'parse-link-header/example/parse' {
  declare module.exports: any;
}

declare module 'parse-link-header/test/parse-link-header' {
  declare module.exports: any;
}

// Filename aliases
declare module 'parse-link-header/example/parse.js' {
  declare module.exports: $Exports<'parse-link-header/example/parse'>;
}
declare module 'parse-link-header/index' {
  declare module.exports: $Exports<'parse-link-header'>;
}
declare module 'parse-link-header/index.js' {
  declare module.exports: $Exports<'parse-link-header'>;
}
declare module 'parse-link-header/test/parse-link-header.js' {
  declare module.exports: $Exports<'parse-link-header/test/parse-link-header'>;
}
