// flow-typed signature: 20c4c7eaa9c696214de6c9314e5360df
// flow-typed version: <<STUB>>/rfc822-date_v^0.0.3/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rfc822-date'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rfc822-date' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'rfc822-date/index' {
  declare module.exports: $Exports<'rfc822-date'>;
}
declare module 'rfc822-date/index.js' {
  declare module.exports: $Exports<'rfc822-date'>;
}
