// flow-typed signature: bc0f5e1b449435351b1d37bbcb0a8a9d
// flow-typed version: <<STUB>>/shiny_v^1.0.0/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shiny'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shiny' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shiny/lib/Classes' {
  declare module.exports: any;
}

declare module 'shiny/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shiny/lib/Classes.js' {
  declare module.exports: $Exports<'shiny/lib/Classes'>;
}
declare module 'shiny/lib/index.js' {
  declare module.exports: $Exports<'shiny/lib/index'>;
}
