// flow-typed signature: 99e3ef9259f0a8ba34740356357e5353
// flow-typed version: <<STUB>>/sqwish_v^0.2.2/flow_v0.44.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sqwish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sqwish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sqwish/src/index' {
  declare module.exports: any;
}

declare module 'sqwish/tests/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sqwish/src/index.js' {
  declare module.exports: $Exports<'sqwish/src/index'>;
}
declare module 'sqwish/tests/tests.js' {
  declare module.exports: $Exports<'sqwish/tests/tests'>;
}
