module.exports =
    Byline      : require './Byline'
    Card        : require './Card'
    Category    : require './Category'
    ContactForm : require './ContactForm'
    Cover       : require './Cover'
    CoverImage  : require './CoverImage'
    CoverCredit : require './CoverCredit'
    DateTime    : require './DateTime'
    Info        : require './Info'
    Summary     : require './Summary'
    Tags        : require './Tags'
    Title       : require './Title'